---
os: Visual Studio 2013

environment:
  GENERATOR: "Visual Studio 12 2013 Win64"
  OPENSSL_DIR: "C:\\Program Files\\OpenSSL"
  BOOST_VERSION: 1.61.0
  BOOST_VERSIONX: 1_61_0
  BOOST_ROOT: "C:\\Boost"
  BOOST_LIBDIR: "C:\\Boost\\lib64-msvc-12.0"
  FLEX_VERSION: 2.4.6

  TARGET: x86_64-pc-windows-gnu
  BITS: 64
  MSYS2: 1
  OPENSSL_VERSION: 1_0_2j

  #matrix:
    # 1.1.0, 64/32 bit
    #- TARGET: i686-pc-windows-gnu
    #  BITS: 32
    #  MSYS2: 1
    #  OPENSSL_VERSION: 1_1_0c
    #- TARGET: x86_64-pc-windows-msvc
    #  BITS: 64
    #  OPENSSL_VERSION: 1_1_0c
    #  OPENSSL_DIR: C:\OpenSSL

    # 1.0.2, 64/32 bit
    #- TARGET: x86_64-pc-windows-gnu
    #  BITS: 64
    #  MSYS2: 1
    #  OPENSSL_VERSION: 1_0_2j
    #- TARGET: i686-pc-windows-msvc
    #  BITS: 32
    #  OPENSSL_VERSION: 1_0_2j
    #  OPENSSL_DIR: C:\OpenSSL

cache:
  - C:\OpenSSL
  - C:\Boost
  - C:\FlexBison

install:
  # install OpenSSL
  - ps: |
      if (Test-Path C:\OpenSSL) {exit}
      Start-FileDownload "http://slproweb.com/download/Win${env:BITS}OpenSSL-${env:OPENSSL_VERSION}.exe"
      Invoke-Expression ".\Win${env:BITS}OpenSSL-${env:OPENSSL_VERSION}.exe /SILENT /VERYSILENT /SP- /DIR=C:\OpenSSL"
  # Install Boost
  - ps: |
      if (Test-Path C:\Boost) {exit}
      Start-FileDownload "http://downloads.sourceforge.net/project/boost/boost-binaries/${env:BOOST_VERSION}/boost_${env:BOOST_VERSIONX}-msvc-12.0-${env:BITS}.exe"
      Invoke-Expression ".\boost_${env:BOOST_VERSIONX}-msvc-12.0-${env:BITS}.exe /SILENT /DIR=C:\Boost"
  # Install Flex
  - ps: |
      if (Test-Path C:\FlexBison) {exit}
      Start-FileDownload "http://downloads.sourceforge.net/project/winflexbison/win_flex_bison-${env:FLEX_VERSION}.zip"
      Expand-Archive win_flex_bison-${env:FLEX_VERSION}.zip -DestinationPath "C:\FlexBison"

before_build:
  - if not exist build (mkdir build)
  - cd build
  - cmake -G "%GENERATOR%" -DCPACK_GENERATOR=WIX -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../inst -DBOOST_ROOT="%BOOST_ROOT%" -DOPENSSL_ROOT_DIR=%OPENSSL_DIR% -DOPENSSL_INCLUDE_DIR=%OPENSSL_DIR%/include -DOPENSSL_LIBRARIES=%OPENSSL_DIR%/lib -DBOOST_LIBRARYDIR="%BOOST_LIBDIR%" -DICINGA2_UNITY_BUILD=ON -DFLEX_EXECUTABLE=C:/FlexBison/win_flex.exe -DBISON_EXECUTABLE=C:/FlexBison/win_bison.exe ..
  - dir build/

# -DICINGA2_WITH_STUDIO=ON -DwxWidgets_ROOT_DIR=c:/local/wxWidgets-3.1.0 -DwxWidgets_LIB_DIR=C:/local/wxWidgets-3.1.0/lib/%wxwidgets_libdir%
# "-DPostgreSQL_ROOT=%postgres_dir%"
